/* Shared i18n + mock data + helpers for all preview variants.
   Loaded via <script src="./shared.js"></script>. Exposes window.PREVIEW. */
(function () {
  const I18N = {
    ru: {
      brand: 'DB GameAgent', brandSub: 'Локальный индекс · игровой агент',
      connected: 'Модель подключена', needEnv: 'Нужен .env с ключом и моделью',
      newChat: 'Новый чат', chats: 'Чаты', requests: 'запросов', deleteChat: 'Удалить',
      documents: 'документов', images: 'изображений',
      rebuildIndex: 'Пересобрать индекс', rebuilding: 'Индексирую…',
      settings: 'Настройки', preferences: 'Параметры', language: 'Язык', theme: 'Тема',
      provider: 'Провайдер', model: 'Модель', modelSearch: 'Поиск модели', manualModel: 'Своя модель',
      memory: 'Память пользователя', tools: 'Инструменты модели',
      akWiki: 'Arknights Wiki', endfieldWiki: 'Endfield Wiki', brave: 'Brave Web',
      sourcesLimit: 'Источников', contextChars: 'Символов контекста',
      historyMessages: 'История сообщений', temperature: 'Температура',
      memoryTitle: 'Память', memoryEmpty: 'Пока пусто — память появится после общения.',
      eyebrow: 'Локальный индекс · внешние источники · облако или локальная модель',
      chatTitle: 'Расскажи об операторе Wišʼadel. Перечисли её сильные стороны и способности.',
      searching: 'Ищу по индексу и вызываю модель…',
      placeholder: 'Спроси про операторов, лор, материалы или что-то другое',
      send: 'Отправить', quickSearch: 'Быстрый поиск', search: 'Искать',
      answerSources: 'Источники ответа', sourcesEmpty: 'Источники появятся после ответа.',
      imageTitle: 'Изображения', imagesEmpty: 'Картинки появятся после запроса.',
      themeDark: 'Тёмная', themeLight: 'Светлая', themeGraphite: 'Графит',
      user: 'Вы', agent: 'Агент',
      welcome: 'Привет. Спроси про операторов, предметы, врагов, стадии или лор. Если база пустая — пересобери индекс.',
      online: 'онлайн', latency: 'отклик', tokens: 'токенов', context: 'контекст',
      apiBase: 'API', collapse: 'Свернуть', copyAnswer: 'Копировать', regenerate: 'Перегенерировать',
      pinChat: 'Закрепить', shareChat: 'Поделиться',
      filterAll: 'Все', filterLore: 'Лор', filterGameplay: 'Геймплей', filterImage: 'Изображения',
      attach: 'Прикрепить', voice: 'Голос', slash: 'Команды',
      modelPicker: 'Выбрать модель', moreSettings: 'Подробные настройки',
      tagSniper: 'Снайпер', tagRanged: 'Дальний', tagDps: 'DPS', tagRarity: 'TIER 6',
      char: 'Оператор', done: 'Готово',
      welcomeTitle: 'Что хочешь узнать?',
      welcomeSub: 'Спроси про базу, операторов, лор или геймплей. Выбери идею ниже или напиши свой вопрос.',
      sug1: 'Сравни Amiya и Kalʼtsit по лору',
      sug2: 'Где фармить D32 Steel в Integrated Strategies',
      sug3: 'Профили операторов с тегом Caster · Crowd Control',
      sug4: 'Сюжетные арки Wišʼadel · хронология',
      thinking: 'Думаю', stepIndex: 'Поиск по индексу', stepWiki: 'Запрос в AK Wiki',
      stepCompose: 'Сборка ответа', stepDone: 'Готово',
      sessionTokens: 'токенов за сессию', uptime: 'аптайм',
      commandPalette: 'Command palette', appearance: 'Внешний вид', dataSources: 'Источники данных',
      retrieval: 'Поиск', generation: 'Генерация',
      sidebarHide: 'Скрыть панель', sidebarShow: 'Показать панель',
      profile: 'Профиль', signOut: 'Выйти', shortcuts: 'Горячие клавиши',
      lib: 'Библиотека', recents: 'Недавние', pinned: 'Закреплённые',
      newOperator: 'Создать запись', newReport: 'Сводка по операторам',
      tabIntel: 'Разведка', tabCompare: 'Сравнение', tabBuilds: 'Билды',
      stat6star: '6★ операторов', statEnemies: 'Врагов', statStages: 'Стадий', statEvents: 'Ивентов',
      timeAgo1: 'только что', timeAgo2: '5 мин назад', timeAgoY: 'вчера', timeAgo2d: '2 дня назад',
      today: 'сегодня',
      chat2: 'Расскажи об операторе Kal\'tsit',
      chat3: 'D32 Steel — где фармить',
      chat4: 'Сравни Amiya и SilverAsh',
      chat5: 'Endfield: разбор древа талантов',
      style: 'Стиль', styleAtlas: 'Atlas · теплый editorial', styleHalo: 'Halo · spatial glass', stylePulse: 'Pulse · плотный pro-tool', styleSynth: 'Synth · AI dev-tool', styleAtelier: 'Atelier · editorial gradient',
      launcherPickStyle: 'Выбери стиль',
      launcherEyebrow: '5 дизайнов · 3 темы · 5 языков',
      launcherTitle: 'Выбери интерфейс на свой вкус.',
      launcherSubtitle: 'Каждый вариант — самостоятельный продукт. Три темы, пять языков, регулируемые панели и адаптивные брейкпоинты. Выбор сохраняется.',
      launcherAtlasDesc: 'Теплая editorial-эстетика в духе Anthropic Claude. Serif-заголовки Newsreader, кремовые тона, янтарный акцент. Спокойный premium-feel для длинных аналитических ответов.',
      launcherHaloDesc: 'Spatial-эстетика в духе Apple visionOS. Frosted glass, атмосферная глубина, аква-акцент, внутренние блики. Три панели, плавающие в пространстве.',
      launcherPulseDesc: 'Плотный pro-tool в духе Linear и Vercel. Высокая плотность, тонкие линии, IBM Plex Mono для метаданных, command palette, hot-keys для каждого действия.',
      launcherSynthDesc: 'AI-native dev-tool в духе Cursor и v0.dev. Navigation rail, titlebar с breadcrumbs, статусбар, prompt-композер с ctx-метром и trace-блоком для агентских шагов.',
      launcherAtelierDesc: 'Editorial в духе Stripe и Notion. Multi-stop gradient brand (pink → purple → blue), Source Serif, hero-карточка профиля с фоновым свечением.',
      launcherOpen: 'Открыть',
      launcherFooter: 'Style picker в шапке любого варианта переключает на лету. Тема и язык сохраняются между сессиями.',
      launcherFooterRight: '5 вариантов'
    },
    en: {
      brand: 'DB GameAgent', brandSub: 'Local index · game-knowledge agent',
      connected: 'Model connected', needEnv: 'Fill .env with an API key and model',
      newChat: 'New chat', chats: 'Chats', requests: 'requests', deleteChat: 'Delete',
      documents: 'documents', images: 'images',
      rebuildIndex: 'Rebuild index', rebuilding: 'Indexing…',
      settings: 'Settings', preferences: 'Preferences', language: 'Language', theme: 'Theme',
      provider: 'Provider', model: 'Model', modelSearch: 'Search models', manualModel: 'Manual model',
      memory: 'User memory', tools: 'Model tool calls',
      akWiki: 'Arknights Wiki', endfieldWiki: 'Endfield Wiki', brave: 'Brave Web',
      sourcesLimit: 'Sources', contextChars: 'Context chars',
      historyMessages: 'History messages', temperature: 'Temperature',
      memoryTitle: 'Memory', memoryEmpty: 'Empty for now — memory will fill as you talk.',
      eyebrow: 'Local index · external sources · cloud or local model',
      chatTitle: 'Tell me about Operator Wišʼadel. List her strengths and abilities.',
      searching: 'Searching the index and calling the model…',
      placeholder: 'Ask about operators, lore, materials, or anything else',
      send: 'Send', quickSearch: 'Quick search', search: 'Search',
      answerSources: 'Answer sources', sourcesEmpty: 'Sources will appear after an answer.',
      imageTitle: 'Images', imagesEmpty: 'Images will appear after a request.',
      themeDark: 'Dark', themeLight: 'Light', themeGraphite: 'Graphite',
      user: 'You', agent: 'Agent',
      welcome: 'Welcome. Ask about operators, items, enemies, stages, or lore. If the database is empty, rebuild the index first.',
      online: 'online', latency: 'latency', tokens: 'tokens', context: 'context',
      apiBase: 'API', collapse: 'Collapse', copyAnswer: 'Copy', regenerate: 'Regenerate',
      pinChat: 'Pin', shareChat: 'Share',
      filterAll: 'All', filterLore: 'Lore', filterGameplay: 'Gameplay', filterImage: 'Images',
      attach: 'Attach', voice: 'Voice', slash: 'Commands',
      modelPicker: 'Pick model', moreSettings: 'Advanced settings',
      tagSniper: 'Sniper', tagRanged: 'Ranged', tagDps: 'DPS', tagRarity: 'TIER 6',
      char: 'Operator', done: 'Done',
      welcomeTitle: 'What would you like to know?',
      welcomeSub: 'Ask about the database, operators, lore, or gameplay. Pick a suggestion below or type your own.',
      sug1: 'Compare Amiya and Kalʼtsit by lore',
      sug2: 'Where to farm D32 Steel in Integrated Strategies',
      sug3: 'Operator profiles with Caster · Crowd Control tags',
      sug4: 'Wišʼadel story arcs · timeline',
      thinking: 'Thinking', stepIndex: 'Searching index', stepWiki: 'AK Wiki lookup',
      stepCompose: 'Composing answer', stepDone: 'Done',
      sessionTokens: 'tokens this session', uptime: 'uptime',
      commandPalette: 'Command palette', appearance: 'Appearance', dataSources: 'Data sources',
      retrieval: 'Retrieval', generation: 'Generation',
      sidebarHide: 'Hide panel', sidebarShow: 'Show panel',
      profile: 'Profile', signOut: 'Sign out', shortcuts: 'Shortcuts',
      lib: 'Library', recents: 'Recents', pinned: 'Pinned',
      newOperator: 'New entry', newReport: 'Operator report',
      tabIntel: 'Intel', tabCompare: 'Compare', tabBuilds: 'Builds',
      stat6star: '6★ operators', statEnemies: 'Enemies', statStages: 'Stages', statEvents: 'Events',
      timeAgo1: 'just now', timeAgo2: '5 min ago', timeAgoY: 'yesterday', timeAgo2d: '2 days ago',
      today: 'today',
      chat2: "Tell me about Operator Kalʼtsit",
      chat3: 'D32 Steel — drop locations',
      chat4: 'Compare Amiya and SilverAsh',
      chat5: 'Endfield: Talent tree breakdown',
      style: 'Style', styleAtlas: 'Atlas · warm editorial', styleHalo: 'Halo · spatial glass', stylePulse: 'Pulse · dense pro-tool', styleSynth: 'Synth · AI dev-tool', styleAtelier: 'Atelier · editorial gradient',
      launcherPickStyle: 'Pick a style',
      launcherEyebrow: '5 designs · 3 themes · 5 languages',
      launcherTitle: 'Pick your interface, your way.',
      launcherSubtitle: 'Each variant is a self-contained product. Three themes, five interface languages, resizable side panels, and adaptive breakpoints. Pick a style — your choice is remembered.',
      launcherAtlasDesc: 'Warm editorial aesthetic in the spirit of Anthropic Claude. Newsreader serif headings, cream tones, amber accent. Calm, premium feel for long analytical answers.',
      launcherHaloDesc: 'Spatial aesthetic in the spirit of Apple visionOS. Frosted glass, atmospheric depth, aqua accent, inner highlights. Three floating panels suspended in space.',
      launcherPulseDesc: 'Dense pro-tool aesthetic in the spirit of Linear and Vercel. High density, fine lines, IBM Plex Mono for metadata, command palette, hot-keys for every action.',
      launcherSynthDesc: 'AI-native dev tool in the spirit of Cursor and v0.dev. Navigation rail, titlebar with breadcrumbs, status bar, prompt composer with context meter and trace block for agent steps.',
      launcherAtelierDesc: 'Editorial aesthetic in the spirit of Stripe and Notion. Multi-stop gradient brand (pink → purple → blue), Source Serif, hero profile card with background glow.',
      launcherOpen: 'Open',
      launcherFooter: "Use the style picker in any variant's header to switch on the fly. Theme + language persist between sessions.",
      launcherFooterRight: '5 variants'
    },
    zh: {
      brand: 'DB GameAgent', brandSub: '本地索引 · 游戏知识代理',
      connected: '模型已连接', needEnv: '请在 .env 中填写 API 密钥与模型',
      newChat: '新对话', chats: '对话', requests: '次', deleteChat: '删除',
      documents: '条文档', images: '张图片',
      rebuildIndex: '重建索引', rebuilding: '索引中…',
      settings: '设置', preferences: '偏好', language: '语言', theme: '主题',
      provider: '服务商', model: '模型', modelSearch: '搜索模型', manualModel: '手动模型',
      memory: '用户记忆', tools: '模型工具',
      akWiki: '明日方舟 Wiki', endfieldWiki: 'Endfield Wiki', brave: 'Brave 网页',
      sourcesLimit: '来源数', contextChars: '上下文字数',
      historyMessages: '历史消息', temperature: '温度',
      memoryTitle: '记忆', memoryEmpty: '暂无 — 对话越多记忆越丰富。',
      eyebrow: '本地索引 · 外部数据源 · 云端或本地模型',
      chatTitle: '介绍干员 Wišʼadel,列出她的强项与能力。',
      searching: '正在检索索引并调用模型…',
      placeholder: '可以问干员、剧情、材料或其他任何事',
      send: '发送', quickSearch: '快速搜索', search: '搜索',
      answerSources: '回答来源', sourcesEmpty: '回答完成后会显示来源。',
      imageTitle: '图片', imagesEmpty: '相关图片将在查询后出现。',
      themeDark: '深色', themeLight: '浅色', themeGraphite: '石墨',
      user: '你', agent: '代理',
      welcome: '你好。可以询问干员、物品、敌人、关卡或剧情。如果数据库为空,请先重建索引。',
      online: '在线', latency: '延迟', tokens: 'tokens', context: '上下文',
      apiBase: 'API', collapse: '折叠', copyAnswer: '复制', regenerate: '重新生成',
      pinChat: '置顶', shareChat: '分享',
      filterAll: '全部', filterLore: '剧情', filterGameplay: '玩法', filterImage: '图片',
      attach: '附件', voice: '语音', slash: '命令',
      modelPicker: '选择模型', moreSettings: '高级设置',
      tagSniper: '狙击', tagRanged: '远程', tagDps: '输出', tagRarity: 'TIER 6',
      char: '干员', done: '完成',
      welcomeTitle: '想了解什么?',
      welcomeSub: '问问数据库、干员、剧情或玩法。选下面的建议或直接输入。',
      sug1: '按剧情对比 Amiya 和 Kalʼtsit',
      sug2: '在集成战略中哪里能刷 D32 Steel',
      sug3: '带 Caster · 群控 标签的干员档案',
      sug4: 'Wišʼadel 剧情线 · 时间轴',
      thinking: '思考中', stepIndex: '检索索引', stepWiki: '查询 AK Wiki',
      stepCompose: '组织回答', stepDone: '完成',
      sessionTokens: '本次会话 tokens', uptime: '运行',
      commandPalette: '命令面板', appearance: '外观', dataSources: '数据源',
      retrieval: '检索', generation: '生成',
      sidebarHide: '隐藏面板', sidebarShow: '显示面板',
      profile: '个人', signOut: '登出', shortcuts: '快捷键',
      lib: '库', recents: '最近', pinned: '置顶',
      newOperator: '新条目', newReport: '干员报告',
      tabIntel: '情报', tabCompare: '对比', tabBuilds: '配装',
      stat6star: '6★ 干员', statEnemies: '敌人', statStages: '关卡', statEvents: '活动',
      timeAgo1: '刚刚', timeAgo2: '5 分钟前', timeAgoY: '昨天', timeAgo2d: '2 天前',
      today: '今天',
      chat2: '介绍干员 Kal\'tsit',
      chat3: 'D32 Steel — 掉落位置',
      chat4: '对比 Amiya 和 SilverAsh',
      chat5: 'Endfield: 天赋树解析',
      style: '风格', styleAtlas: 'Atlas · 温暖编辑风', styleHalo: 'Halo · 空间玻璃', stylePulse: 'Pulse · 紧凑专业', styleSynth: 'Synth · AI 开发工具', styleAtelier: 'Atelier · 编辑渐变',
      launcherPickStyle: '选择风格',
      launcherEyebrow: '5 种设计 · 3 种主题 · 5 种语言',
      launcherTitle: '按你的喜好挑选界面。',
      launcherSubtitle: '每个变体都是独立产品。三种主题,五种界面语言,可调整大小的侧边栏和自适应断点。选择会被记住。',
      launcherAtlasDesc: '类似 Anthropic Claude 的温暖编辑美学。Newsreader 衬线标题、奶油色调、琥珀色强调。沉稳的高端质感,适合长篇分析答案。',
      launcherHaloDesc: '类似 Apple visionOS 的空间美学。磨砂玻璃、氛围深度、青色强调、内部高光。三块悬浮在空间中的面板。',
      launcherPulseDesc: '类似 Linear 和 Vercel 的高密度专业工具。紧凑布局、细线、IBM Plex Mono 用于元数据、命令面板、每个动作都有快捷键。',
      launcherSynthDesc: '类似 Cursor 和 v0.dev 的 AI 原生开发工具。导航栏、带面包屑的标题栏、状态栏、带上下文计数和代理步骤跟踪块的提示编辑器。',
      launcherAtelierDesc: '类似 Stripe 和 Notion 的编辑美学。多停渐变品牌(粉 → 紫 → 蓝)、Source Serif、带背景光晕的英雄档案卡片。',
      launcherOpen: '打开',
      launcherFooter: '任意变体顶栏的风格选择器即时切换。主题和语言在会话间保持。',
      launcherFooterRight: '5 个变体'
    },
    ja: {
      brand: 'DB GameAgent', brandSub: 'ローカル索引 · ゲーム知識エージェント',
      connected: 'モデル接続済み', needEnv: '.env に API キーとモデルを設定',
      newChat: '新規チャット', chats: 'チャット', requests: '件', deleteChat: '削除',
      documents: 'ドキュメント', images: '画像',
      rebuildIndex: 'インデックス再構築', rebuilding: '索引中…',
      settings: '設定', preferences: '環境設定', language: '言語', theme: 'テーマ',
      provider: 'プロバイダ', model: 'モデル', modelSearch: 'モデル検索', manualModel: '手動モデル',
      memory: 'ユーザーメモリ', tools: 'モデルツール',
      akWiki: 'アークナイツ Wiki', endfieldWiki: 'Endfield Wiki', brave: 'Brave Web',
      sourcesLimit: 'ソース数', contextChars: 'コンテキスト文字数',
      historyMessages: '履歴メッセージ', temperature: '温度',
      memoryTitle: 'メモリ', memoryEmpty: '空 — 会話するほどメモリが増えます。',
      eyebrow: 'ローカル索引 · 外部ソース · クラウド/ローカルモデル',
      chatTitle: 'オペレーター Wišʼadel について教えて。強みと能力を列挙して。',
      searching: '索引を検索しモデルを呼び出し中…',
      placeholder: 'オペレーター、ロア、素材、何でも質問できます',
      send: '送信', quickSearch: 'クイック検索', search: '検索',
      answerSources: '回答ソース', sourcesEmpty: '回答後にソースが表示されます。',
      imageTitle: '画像', imagesEmpty: 'リクエスト後に画像が表示されます。',
      themeDark: 'ダーク', themeLight: 'ライト', themeGraphite: 'グラファイト',
      user: 'あなた', agent: 'エージェント',
      welcome: 'ようこそ。オペレーター・アイテム・敵・ステージ・ロアを質問できます。データベースが空ならまずインデックスを再構築してください。',
      online: 'オンライン', latency: '遅延', tokens: 'tokens', context: 'コンテキスト',
      apiBase: 'API', collapse: '折りたたむ', copyAnswer: 'コピー', regenerate: '再生成',
      pinChat: 'ピン留め', shareChat: '共有',
      filterAll: 'すべて', filterLore: 'ロア', filterGameplay: 'ゲームプレイ', filterImage: '画像',
      attach: '添付', voice: '音声', slash: 'コマンド',
      modelPicker: 'モデル選択', moreSettings: '詳細設定',
      tagSniper: 'スナイパー', tagRanged: '遠距離', tagDps: 'DPS', tagRarity: 'TIER 6',
      char: 'オペレーター', done: '完了',
      welcomeTitle: '何を知りたい?',
      welcomeSub: 'データベース、オペレーター、ロア、ゲームプレイについて聞いてください。下の候補から選ぶか直接入力。',
      sug1: 'Amiya と Kalʼtsit をロアで比較',
      sug2: '統合戦略で D32 Steel をどこで集める',
      sug3: 'Caster · 群体制御 タグのオペレータープロフィール',
      sug4: 'Wišʼadel のストーリーアーク · タイムライン',
      thinking: '思考中', stepIndex: '索引検索', stepWiki: 'AK Wiki 参照',
      stepCompose: '回答構築', stepDone: '完了',
      sessionTokens: 'セッション tokens', uptime: '稼働時間',
      commandPalette: 'コマンドパレット', appearance: '外観', dataSources: 'データソース',
      retrieval: '検索', generation: '生成',
      sidebarHide: 'パネルを隠す', sidebarShow: 'パネルを表示',
      profile: 'プロフィール', signOut: 'サインアウト', shortcuts: 'ショートカット',
      lib: 'ライブラリ', recents: '最近', pinned: 'ピン留め',
      newOperator: '新規エントリ', newReport: 'オペレーターレポート',
      tabIntel: 'インテル', tabCompare: '比較', tabBuilds: 'ビルド',
      stat6star: '6★ オペレーター', statEnemies: '敵', statStages: 'ステージ', statEvents: 'イベント',
      timeAgo1: 'たった今', timeAgo2: '5分前', timeAgoY: '昨日', timeAgo2d: '2日前',
      today: '今日',
      chat2: 'オペレーター Kal\'tsit について',
      chat3: 'D32 Steel — ドロップ場所',
      chat4: 'Amiya と SilverAsh の比較',
      chat5: 'Endfield: タレントツリー解析',
      style: 'スタイル', styleAtlas: 'Atlas · 暖かいエディトリアル', styleHalo: 'Halo · スペーシャルグラス', stylePulse: 'Pulse · 密度の高いプロツール', styleSynth: 'Synth · AI 開発ツール', styleAtelier: 'Atelier · エディトリアルグラデ',
      launcherPickStyle: 'スタイルを選択',
      launcherEyebrow: '5 デザイン · 3 テーマ · 5 言語',
      launcherTitle: 'あなた好みのインターフェイスを選ぼう。',
      launcherSubtitle: '各バリアントは独立した製品です。3 つのテーマ、5 言語、リサイズ可能なパネル、適応的ブレイクポイント。選択は記憶されます。',
      launcherAtlasDesc: 'Anthropic Claude 風の温かみのあるエディトリアル。Newsreader セリフ見出し、クリーム調、アンバーアクセント。長文の分析回答に最適な落ち着いた高級感。',
      launcherHaloDesc: 'Apple visionOS 風の空間的美学。すりガラス、立体感、アクアアクセント、内側のハイライト。空間に浮かぶ 3 つのパネル。',
      launcherPulseDesc: 'Linear や Vercel 風の高密度プロツール。緊密なレイアウト、細線、メタデータ用 IBM Plex Mono、コマンドパレット、すべてのアクションにホットキー。',
      launcherSynthDesc: 'Cursor や v0.dev 風の AI ネイティブ開発ツール。ナビゲーションレール、パンくず付きタイトルバー、ステータスバー、コンテキストメーターとトレースブロック付きプロンプト。',
      launcherAtelierDesc: 'Stripe や Notion 風のエディトリアル。マルチストップグラデーションブランド(ピンク → 紫 → ブルー)、Source Serif、背景グロー付きヒーローカード。',
      launcherOpen: '開く',
      launcherFooter: 'どのバリアントもヘッダーのスタイルピッカーで即時切り替え。テーマと言語はセッション間で保持されます。',
      launcherFooterRight: '5 バリアント'
    },
    ko: {
      brand: 'DB GameAgent', brandSub: '로컬 인덱스 · 게임 지식 에이전트',
      connected: '모델 연결됨', needEnv: '.env 에 API 키와 모델을 입력',
      newChat: '새 채팅', chats: '채팅', requests: '회', deleteChat: '삭제',
      documents: '문서', images: '이미지',
      rebuildIndex: '인덱스 재구축', rebuilding: '색인 중…',
      settings: '설정', preferences: '환경설정', language: '언어', theme: '테마',
      provider: '공급자', model: '모델', modelSearch: '모델 검색', manualModel: '수동 모델',
      memory: '사용자 메모리', tools: '모델 도구',
      akWiki: '명일방주 Wiki', endfieldWiki: 'Endfield Wiki', brave: 'Brave 웹',
      sourcesLimit: '소스 수', contextChars: '컨텍스트 글자수',
      historyMessages: '히스토리', temperature: '온도',
      memoryTitle: '메모리', memoryEmpty: '비어 있음 — 대화하면 메모리가 쌓입니다.',
      eyebrow: '로컬 인덱스 · 외부 소스 · 클라우드/로컬 모델',
      chatTitle: '오퍼레이터 Wišʼadel 에 대해 알려줘. 강점과 능력을 나열해.',
      searching: '인덱스 검색 및 모델 호출 중…',
      placeholder: '오퍼레이터, 로어, 재료 등 무엇이든 물어보세요',
      send: '전송', quickSearch: '빠른 검색', search: '검색',
      answerSources: '답변 소스', sourcesEmpty: '답변 후 소스가 표시됩니다.',
      imageTitle: '이미지', imagesEmpty: '요청 후 관련 이미지가 표시됩니다.',
      themeDark: '다크', themeLight: '라이트', themeGraphite: '그래파이트',
      user: '나', agent: '에이전트',
      welcome: '환영합니다. 오퍼레이터·아이템·적·스테이지·로어에 대해 물어볼 수 있어. 데이터베이스가 비어있다면 먼저 인덱스를 재구축해.',
      online: '온라인', latency: '지연', tokens: '토큰', context: '컨텍스트',
      apiBase: 'API', collapse: '접기', copyAnswer: '복사', regenerate: '다시 생성',
      pinChat: '고정', shareChat: '공유',
      filterAll: '전체', filterLore: '로어', filterGameplay: '게임플레이', filterImage: '이미지',
      attach: '첨부', voice: '음성', slash: '명령',
      modelPicker: '모델 선택', moreSettings: '고급 설정',
      tagSniper: '스나이퍼', tagRanged: '원거리', tagDps: 'DPS', tagRarity: 'TIER 6',
      char: '오퍼레이터', done: '완료',
      welcomeTitle: '무엇을 알고 싶어요?',
      welcomeSub: '데이터베이스, 오퍼레이터, 로어 또는 게임플레이에 대해 물어보세요.',
      sug1: 'Amiya와 Kalʼtsit 를 로어로 비교',
      sug2: '통합 전략에서 D32 Steel 어디서 파밍?',
      sug3: 'Caster · 군중 제어 태그 오퍼레이터 프로필',
      sug4: 'Wišʼadel 스토리 아크 · 타임라인',
      thinking: '생각 중', stepIndex: '인덱스 검색', stepWiki: 'AK Wiki 조회',
      stepCompose: '답변 구성', stepDone: '완료',
      sessionTokens: '세션 토큰', uptime: '가동시간',
      commandPalette: '명령 팔레트', appearance: '외관', dataSources: '데이터 소스',
      retrieval: '검색', generation: '생성',
      sidebarHide: '패널 숨기기', sidebarShow: '패널 표시',
      profile: '프로필', signOut: '로그아웃', shortcuts: '단축키',
      lib: '라이브러리', recents: '최근', pinned: '고정',
      newOperator: '새 항목', newReport: '오퍼레이터 리포트',
      tabIntel: '인텔', tabCompare: '비교', tabBuilds: '빌드',
      stat6star: '6★ 오퍼레이터', statEnemies: '적', statStages: '스테이지', statEvents: '이벤트',
      timeAgo1: '방금', timeAgo2: '5분 전', timeAgoY: '어제', timeAgo2d: '2일 전',
      today: '오늘',
      chat2: '오퍼레이터 Kal\'tsit 에 대해',
      chat3: 'D32 Steel — 드랍 위치',
      chat4: 'Amiya와 SilverAsh 비교',
      chat5: 'Endfield: 특성 트리 분석',
      style: '스타일', styleAtlas: 'Atlas · 따뜻한 에디토리얼', styleHalo: 'Halo · 공간 글래스', stylePulse: 'Pulse · 조밀한 프로 툴', styleSynth: 'Synth · AI 개발 툴', styleAtelier: 'Atelier · 에디토리얼 그라데이션',
      launcherPickStyle: '스타일 선택',
      launcherEyebrow: '5개 디자인 · 3개 테마 · 5개 언어',
      launcherTitle: '취향에 맞는 인터페이스를 선택하세요.',
      launcherSubtitle: '각 변형은 독립적인 제품입니다. 세 가지 테마, 다섯 가지 언어, 크기 조절 가능한 사이드 패널, 적응형 브레이크포인트. 선택은 기억됩니다.',
      launcherAtlasDesc: 'Anthropic Claude 스타일의 따뜻한 에디토리얼 미학. Newsreader 세리프 헤딩, 크림 톤, 앰버 강조. 긴 분석 답변에 어울리는 차분한 프리미엄 감각.',
      launcherHaloDesc: 'Apple visionOS 스타일의 공간 미학. 프로스티드 글래스, 분위기 깊이, 아쿠아 강조, 내부 하이라이트. 공간에 떠 있는 세 개의 패널.',
      launcherPulseDesc: 'Linear와 Vercel 스타일의 조밀한 프로 툴. 높은 밀도, 가는 선, 메타데이터용 IBM Plex Mono, 명령 팔레트, 모든 작업의 단축키.',
      launcherSynthDesc: 'Cursor와 v0.dev 스타일의 AI 네이티브 개발 툴. 내비게이션 레일, 브레드크럼 타이틀바, 상태 표시줄, 컨텍스트 미터와 추적 블록이 있는 프롬프트 작성기.',
      launcherAtelierDesc: 'Stripe와 Notion 스타일의 에디토리얼. 멀티 스톱 그라디언트 브랜드(핑크 → 보라 → 블루), Source Serif, 배경 빛이 있는 히어로 프로필 카드.',
      launcherOpen: '열기',
      launcherFooter: '어떤 변형의 헤더에 있는 스타일 선택기로도 즉시 전환됩니다. 테마와 언어는 세션 간에 유지됩니다.',
      launcherFooterRight: '5개 변형'
    }
  };

  const MOCK = {
    health: { documents: 51210, images: 28122, online: true, latency: 142, provider: 'bothub', model: 'grok-4.3', modelConfigured: true, sessionTokens: 14732, uptime: '02:14:38' },
    counters: { operators6star: 134, enemies: 412, stages: 1284, events: 87 },
    chats: [
      { id: 'c1', titleKey: 'chatTitle', count: 1, active: true, pinned: false, when: 'timeAgo1', whenLit: '13:42' },
      { id: 'c2', titleKey: 'chat2', count: 1, active: false, pinned: false, when: 'timeAgo2', whenLit: '12:08' },
      { id: 'c3', titleKey: 'chat3', count: 3, active: false, pinned: true, when: 'timeAgoY', whenLit: 'Yesterday' },
      { id: 'c4', titleKey: 'chat4', count: 5, active: false, pinned: false, when: 'timeAgo2d', whenLit: '2 days' },
      { id: 'c5', titleKey: 'chat5', count: 2, active: false, pinned: false, when: 'timeAgo2d', whenLit: '3 days' }
    ],
    sources: [
      { category: 'LORE', source: 'STORY_JSON', title: 'When Sorrow Blooms #21', snippet: "…I'm just taking him away with [me]. [Wiš][adel]: He already died once, so it's not hard to guess why [Her] Highness let him remain here…", score: 0.94 },
      { category: 'LORE', source: 'STORY_JSON', title: 'All the Unrevealed #13', snippet: "…[Wiš][adel]: So as a thank-you, how [about] I invite you to watch the Catastrophe cloud with [me]? You're here to 'explore', right? Paryaqaqa: Hahaha…", score: 0.92 },
      { category: 'LORE', source: 'STORY_JSON', title: 'All the Unrevealed #12', snippet: "…[and] hesitates [about] whether to make a move. ???: This guy's the one you were talking [about]? [Wiš][adel]: He looks pretty normal to [me].", score: 0.91 },
      { category: 'GAMEPLAY', source: 'character_table.json', title: 'Wišʼadel · skill scaling', snippet: 'Localized Liquidation: aftershocks deal scaled ATK × 0.85. Saturated Vengeance manual overload bursts 4 hits at scaled ATK on random targets in range.', score: 0.88 },
      { category: 'LORE', source: 'STORY_JSON', title: 'Another Breath of Death #3', snippet: "…We can't just sit back [and] watch. You can [tell] us [about] your idea on the way. [Wiš][adel]: Hmph. Two dunces. [Wiš][adel]: What [about] you…", score: 0.87 },
      { category: 'GAMEPLAY', source: 'token_table.json', title: 'Revenantʼs Shadow · summon stats', snippet: 'HP 3500 · ATK 660–777 · DEF 520–650 · RES 50%. Arts damage, applies Slow, attaches shadow, grants 0–2 SP.', score: 0.85 },
      { category: 'LORE', source: 'STORY_JSON', title: 'Night Goes Gentle #3', snippet: "…[Wiš][adel]: Bunny? Why do you look like…? Amiya: [Wiš][adel]:…? What [about] [me]…? [Wiš][adel]: Forget it! [Wiš][adel]: Did we end up in Londinium…", score: 0.83 },
      { category: 'GAMEPLAY', source: 'item_table.json', title: 'Wišʼadelʼs Token · upgrade path', snippet: 'p_char_1035_wisdel — grenade-style item that raises Potential. Stage drops + Originium Pearl exchange.', score: 0.81 }
    ],
    images: [
      { id: 'i1', url: 'https://placehold.co/240x240/2a2218/d7b46a/png?text=Wi%C5%A1%CA%BCadel', name: 'wisdel_card.png' },
      { id: 'i2', url: 'https://placehold.co/240x240/1f3030/73b7b1/png?text=Skin+1', name: 'wisdel_skin1.png' },
      { id: 'i3', url: 'https://placehold.co/240x240/2b1f1f/e26d5c/png?text=Promo+E2', name: 'wisdel_e2.png' },
      { id: 'i4', url: 'https://placehold.co/240x240/2a2230/9c8dff/png?text=Revenant', name: 'token_wward.png' },
      { id: 'i5', url: 'https://placehold.co/240x240/22262a/c7ccd1/png?text=Sketch', name: 'wisdel_sketch.png' },
      { id: 'i6', url: 'https://placehold.co/240x240/24322e/4ad295/png?text=Banner', name: 'wisdel_banner.png' }
    ],
    providers: [
      { id: 'bothub', label: 'BotHub', model: 'gpt-5.5', configured: true },
      { id: 'openai', label: 'OpenAI', model: 'gpt-5', configured: true },
      { id: 'anthropic', label: 'Anthropic', model: 'claude-sonnet-4-6', configured: true },
      { id: 'xai', label: 'xAI · Grok', model: 'grok-4.3', configured: true },
      { id: 'local', label: 'Local · Ollama', model: 'llama-4-70b', configured: false }
    ],
    models: ['grok-4.3', 'gpt-5.5', 'gpt-5', 'claude-sonnet-4-6', 'claude-opus-4-7', 'llama-4-70b', 'gemini-2.5-pro'],
    messages: [
      { role: 'assistant', welcome: true },
      { role: 'user', contentKey: 'chatTitle' },
      {
        role: 'assistant',
        markdown: true,
        steps: ['stepIndex', 'stepWiki', 'stepCompose', 'stepDone'],
        content: `**Operator Wišʼadel** (ID: char_1035_wisdel)\n\n*Category:* Operator (from gamedata_en / character_table.json)\n*Rarity:* TIER 6 · *Profession:* SNIPER · *Position:* RANGED · *Tags:* DPS\n\n**Core Attack:** Deals two instances of Physical damage to ground enemies in a small area (second hit is a shockwave at half normal ATK).\n\n**Skills** (source: character_table.json):\n\n- **Localized Liquidation** — Next attack triggers 2 extra aftershocks, stuns targets, slightly larger splash area, aftershocks deal scaled ATK.\n- **Saturated Vengeance** — +ATK, reduced attack interval, hits 3 enemies simultaneously. Manual Overload: 4 rapid hits at scaled ATK on random targets in range.\n\n**Summon** (Revenantʼs Shadow, ID: token_10035_wisdel_wward):\nAttacks in Wišʼadelʼs range with Arts damage, applies Slow, attaches shadow, grants 0–2 SP. Stats (level 1): HP 3500, ATK 660–777, DEF 520–650, RES 50%.\n\n**Strengths** (database inference): Strong multi-target Physical DPS with built-in area/crowd control (stun + shockwave), flexible burst via aftershocks and overload, plus utility from summon (slow + SP regen). Ideal for ground-focused AoE pressure and sustained fights.\n\n*Item tie-in:* Wišʼadelʼs Token (p_char_1035_wisdel) — grenade-style item for Potential increase.`
      }
    ],
    memoryEntries: [
      { key: 'role', value: 'Player · keeping farm sheets per operator' },
      { key: 'favorite', value: "Wišʼadel, Kalʼtsit" },
      { key: 'roster_focus', value: '6★ Snipers + Casters' }
    ],
    suggestions: ['sug1', 'sug2', 'sug3', 'sug4']
  };

  function applyLang(root, lang) {
    const dict = I18N[lang] || I18N.en;
    root.setAttribute('data-lang', lang);
    root.querySelectorAll('[data-i18n]').forEach((el) => {
      const key = el.getAttribute('data-i18n');
      if (dict[key] !== undefined) el.textContent = dict[key];
    });
    root.querySelectorAll('[data-i18n-attr]').forEach((el) => {
      const spec = el.getAttribute('data-i18n-attr');
      spec.split(';').forEach((pair) => {
        const [attr, key] = pair.split(':').map((s) => s.trim());
        if (attr && key && dict[key] !== undefined) el.setAttribute(attr, dict[key]);
      });
    });
    return dict;
  }

  function applyTheme(root, theme) { root.setAttribute('data-theme', theme); }
  function getStored(k, fb) { try { return localStorage.getItem(k) || fb; } catch { return fb; } }
  function setStored(k, v) { try { localStorage.setItem(k, v); } catch {} }

  // Simple markdown → HTML (subset, just enough for the demo)
  function md(src) {
    return src
      .replace(/&/g, '&amp;').replace(/</g, '&lt;')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .split(/\n\n+/).map((p) => {
        if (p.startsWith('- ')) {
          return '<ul>' + p.split(/\n- /).map((i) => `<li>${i.replace(/^- /, '').trim()}</li>`).join('') + '</ul>';
        }
        return `<p>${p.replace(/\n/g, '<br/>')}</p>`;
      }).join('');
  }

  function fmtNum(n, sep = ' ') {
    return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, sep);
  }

  function bindStylePicker(selectId) {
    const el = document.getElementById(selectId || 'style-select');
    if (!el) return;
    const here = (location.pathname.split('/').pop() || '').toLowerCase() || 'atlas.html';
    el.value = here;
    el.addEventListener('change', (e) => {
      try { localStorage.setItem('preview-style', e.target.value); } catch {}
      window.location.href = e.target.value;
    });
  }

  window.PREVIEW = { I18N, MOCK, applyLang, applyTheme, getStored, setStored, md, fmtNum, bindStylePicker };
})();
